config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  resources :twitters do
    member do
      get 'buscador'
    end
    collection do
      get "search"
    end
  end 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "twitters#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/twitter.rb
class Twitter < ApplicationRecord
    include PgSearch::Model

    pg_search_scope :search_full_text,
    against: {
        username:  'A',
        description: 'B',
    },
    using: {
        tsearch: {
            prefix: true,      # Coincidencias de prefijo
            any_word: true,    # Coincidencias intermedias
            dictionary: "spanish"  # Diccionario para búsqueda en español (opcional, reemplaza "spanish" según necesites)
        }
    }
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    Pagy::DEFAULT[:items] = 10
    include Pagy::Backend   

    require 'pagy'
    #Pagy::I18n.load(locale: 'es', filepath: 'config/locales/es.yml')
end

app/controllers/twitters_controller.rb
class TwittersController < ApplicationController
  before_action :set_twitter, only: %i[ show edit update destroy ]

  def buscador
  end
  
  
  # GET /twitters or /twitters.json
  def index
    @pagy, @twitters = pagy(Twitter.order(created_at: :desc))
    if params[:query_text].present?
      @pagy, @twitters = pagy(Twitter.search_full_text(params[:query_text]))
    end 
  end

  # GET /twitters/1 or /twitters/1.json
  def show
  end

  # GET /twitters/new
  def new
    @twitter = Twitter.new
  end

  # GET /twitters/1/edit
  def edit
  end

  # POST /twitters or /twitters.json
  def create
    @twitter = Twitter.new(twitter_params)

    respond_to do |format|
      if @twitter.save
        format.html { redirect_to twitter_url(@twitter), notice: "Twitter creado" }
        format.json { render :show, status: :created, location: @twitter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @twitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twitters/1 or /twitters/1.json
  def update
    respond_to do |format|
      if @twitter.update(twitter_params)
        format.html { redirect_to twitter_url(@twitter), notice: "Twitter editado" }
        format.json { render :show, status: :ok, location: @twitter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @twitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitters/1 or /twitters/1.json
  def destroy
    @twitter.destroy

    respond_to do |format|
      format.html { redirect_to twitters_url, notice: "Twitter destruido" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twitter
      @twitter = Twitter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twitter_params
      params.require(:twitter).permit(:username, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/twitters_helper.rb
module TwittersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClonTwitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>

  <body>

  <div class="container">
    <div class="row">
      
      <div class="col order-last ">
        <%= render "cajabuscadora" %> 
      </div>
    
      <div class="col-6">
        <div class="sticky-sm-top">
          <nav class="navbar bg-body-tertiary">    
            <div class="container-fluid">
              <a class="navbar-brand" href="<%= twitters_path %>">HOME</a>
            </div>
          </nav>    
        </div>
        <%= yield %>
      </div>
    
      <div class="col order-first">
        <%= render "izquierdo" %>        
      </div>
    
    </div>
  </div>

  
 
    
      
    </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script> 
    
  </body>
</html>

app/views/twitters/_cajabuscadora.html.erb
<ul style="list-style: none;">
    <br>
    <br>
    <li>
        <h6>Buscador</h6>
    </li>
    <br>
    
    <li>
        <%= form_with url: twitters_path, method: :get do |form| %>
                
        <%= form.text_field :query_text, placeholder: 'Escribe AQUI', value: params[:query_text] %>
                
        <%= form.submit "Buscar" %>
        <% end %>
                
    </li> 
</ul>        

app/views/twitters/_form.html.erb
<%= form_with(model: twitter) do |form| %>
  <% if twitter.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(twitter.errors.count, "error") %> prohibited this twitter from being saved:</h2>

      <ul>
        <% twitter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit "Sube el Twitt" %>
  </div>
<% end %>

app/views/twitters/_izquierdo.html.erb
<nav class="sticky-top bg-body">
    <div class="container col-md-auto">
        <ul style="list-style: none;">
            <br>
            <br>
            <li>
                <a class="navbar-brand" href="<%= twitters_path %>">
                    <img src="<%= asset_path "im.jpg" %>" alt="Clon twitter" width="50" height="50">
                </a>
            </li>
            <br>
            <br>
            <li>
                <a class="navbar-brand" href="<%= @twitter %>">
                    <img src="<%= asset_path "buscar.jpg" %>" alt="Buscar" width="50" height="50">
                </a>
            </li>
            <br>
            <br>
            <li>  
                <a class="navbar-brand margin" href="#">
                  <img src="<%= asset_path "campana.jpg" %>" alt="Los nuevos" width="50" height="50">
                </a>
            </li>
            <br>
            <br>
            <li>  
                <a class="navbar-brand" href="<%= new_twitter_path %>">
                  <img src="<%= asset_path "nuevo.jpg" %>" alt="Crear nuevo" width="50" height="50">
                </a>
            </li> 
        </ul>        
    </div>
</nav>

app/views/twitters/_twitter.html.erb
<div id="<%= dom_id twitter %>">
  <p>
    <strong>User</strong>
    <%= twitter.username %>
  </p>

  <p>
    <strong>La Mierda q desparramó:</strong>
    <%= twitter.description %>
  </p>

</div>

app/views/twitters/_ultimo_twett.html.erb
<div id="twitter">
  <div class="border">
    <%= render @twitter %>
  </div> 
</div>

app/views/twitters/buscador.html.erb
<%= Twitter.find(params["username"]).name %>

app/views/twitters/edit.html.erb
<h1>Editar Twitter</h1>

<%= render "form", twitter: @twitter %>

<br>

<div>
  <%= link_to "Mostrar el Twitt", @twitter %> |
  <%= link_to "Home", twitters_path %>
</div>

app/views/twitters/index.html.erb
<div>

  <p style="color: green"><%= notice %></p>
  <div class="border border-info, text-center " style="padding-top: 20px; padding-bottom: 20px;">
    <h1>Qué sucede!?</h1>
      
    
    <div class="text-center" style="margin-top: 20px; margin-bottom: 20px;">
      <%= link_to "Nuevo Twitt", new_twitter_path %>
    </div>

  </div>
    
  <div id="twitters">
    <% @twitters.each do |twitter| %>
      <div class="border">
          
        <%= render twitter %>
          
        <p style="margin: 30px;">
          <%= link_to "Mostrar este twitt", twitter %>
        </p>
      </div> 
    <% end %>
  </div>
  
  <div class="border-info, text-center" style="padding-top: 20px; padding-bottom: 20px;">
    <%=raw pagy_nav(@pagy)%>
  </div>
</div>

app/views/twitters/new.html.erb
<div class="border">
  <h1 class= "text-center">Nuevo Twitt</h1>

  <%= render "form", twitter: @twitter %>

  <br>

  <div class= "text-center" >
    <%= link_to "Home", twitters_path %>
  </div>
</div>

app/views/twitters/search.html.erb
<% Twitter.all.each do |x| %>
    <%= x.username %> <br>
    <hr>
<% end %>

app/views/twitters/show.html.erb
<p style="color: green"><%= notice %></p>

  
  
<div class="border">
  <%= render @twitter %>

  <div>
    <%= link_to "Editar Twitt", edit_twitter_path(@twitter) %> |
    <%= link_to "A Home", twitters_path %>
    
    <%= button_to "Destruir twitt", @twitter, method: :delete %>

  </div>
</div>